// <auto-generated />
using System;
using JIUAPI.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JIUAPI.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JIUAPI.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Belt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassesNeededForPromotion")
                        .HasColumnType("int");

                    b.Property<int>("MaxDegrees")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Belts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassesNeededForPromotion = 20,
                            MaxDegrees = 4,
                            Name = "Branca",
                            Order = 0
                        },
                        new
                        {
                            Id = 2,
                            ClassesNeededForPromotion = 20,
                            MaxDegrees = 4,
                            Name = "Azul",
                            Order = 1
                        },
                        new
                        {
                            Id = 3,
                            ClassesNeededForPromotion = 20,
                            MaxDegrees = 4,
                            Name = "Roxa",
                            Order = 2
                        },
                        new
                        {
                            Id = 4,
                            ClassesNeededForPromotion = 20,
                            MaxDegrees = 4,
                            Name = "Marrom",
                            Order = 3
                        },
                        new
                        {
                            Id = 5,
                            ClassesNeededForPromotion = 0,
                            MaxDegrees = 10,
                            Name = "Preta",
                            Order = 4
                        });
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClassDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InstructorUserId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassesCompleted")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBeltId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentDegree")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBeltId");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.StudentBeltHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeltId")
                        .HasColumnType("int");

                    b.Property<int>("DegreeAchieved")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PromotedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeltId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentBeltHistories");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("JIUAPI.Domain.Entities.Class", "Class")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JIUAPI.Domain.Entities.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Class", b =>
                {
                    b.HasOne("JIUAPI.Domain.Entities.ApplicationUser", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Student", b =>
                {
                    b.HasOne("JIUAPI.Domain.Entities.Belt", "CurrentBelt")
                        .WithMany()
                        .HasForeignKey("CurrentBeltId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JIUAPI.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentBelt");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.StudentBeltHistory", b =>
                {
                    b.HasOne("JIUAPI.Domain.Entities.Belt", "Belt")
                        .WithMany("StudentBeltHistories")
                        .HasForeignKey("BeltId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JIUAPI.Domain.Entities.Student", "Student")
                        .WithMany("BeltHistories")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Belt");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Belt", b =>
                {
                    b.Navigation("StudentBeltHistories");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Class", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("JIUAPI.Domain.Entities.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("BeltHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
